blueprint:
  name: Frigate Identity - All Children Home
  description: >
    Send a notification when every child in your household has been detected
    on a camera inside the home during a configured time window.  Useful as
    a "everyone is home safe" evening confirmation.
  domain: automation
  input:
    children_names:
      name: Children Names
      description: >
        List of children's names to track (as detected by Frigate Identity).
        All children in this list must be detected before the notification fires.
      default: ["Alice", "Bob"]
      selector:
        object:
    home_cameras:
      name: Home Cameras
      description: >
        List of Frigate camera names that are inside the home or at the front door.
        A child is considered home when detected on one of these cameras.
      default: ["front_door", "hallway", "living_room"]
      selector:
        object:
    notify_service:
      name: Notification Service
      description: The notification service to use (e.g. mobile_app_pixel_8)
      selector:
        text:
    check_after:
      name: Start Checking After
      description: Only fire the notification after this time (e.g. school dismissal)
      default: "14:00:00"
      selector:
        time:
    check_before:
      name: Stop Checking Before
      description: Stop checking after this time (e.g. late night)
      default: "22:00:00"
      selector:
        time:
    cooldown_hours:
      name: Daily Cooldown
      description: >
        Minimum hours between notifications (prevents repeated alerts on the same
        evening if a child briefly leaves and comes back).
      default: 4
      selector:
        number:
          min: 1
          max: 12
          unit_of_measurement: hours

mode: single
max_exceeded: silent

trigger:
  # Re-evaluate whenever the All Persons sensor updates
  - platform: state
    entity_id: sensor.frigate_identity_all_persons

variables:
  children_var: !input children_names
  home_cameras_var: !input home_cameras
  notify_service_var: !input notify_service

condition:
  # Only during the check window
  - condition: time
    after: !input check_after
    before: !input check_before
  # Every child in the list must be detected on a home camera
  - condition: template
    value_template: >
      {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
      {% if not persons %}
        {{ false }}
      {% else %}
        {% set all_home = namespace(value=true) %}
        {% for child in children_var %}
          {% if child not in persons or persons[child].camera not in home_cameras_var %}
            {% set all_home.value = false %}
          {% endif %}
        {% endfor %}
        {{ all_home.value }}
      {% endif %}

action:
  - service: "notify.{{ notify_service_var }}"
    data:
      title: "ðŸ  Everyone is Home"
      message: >
        All children are home:
        {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
        {% for child in children_var %}
          {{ child }} ({{ persons[child].camera }}){% if not loop.last %}, {% endif %}
        {% endfor %}
      data:
        tag: "all_children_home"

  - delay:
      hours: !input cooldown_hours
