blueprint:
  name: Frigate Identity - Supervision Detection
  description: >
    Create a binary sensor that detects if a child is supervised.

    A child is considered supervised when any trusted adult was seen within the
    configured timeout AND either shares the same Frigate camera OR shares at
    least one active Frigate zone with the child.

    The zone-based check is critical for large yards with multiple cameras: an
    adult visible on camera B supervises a child on camera A as long as both
    are in the same zone (e.g. "play_area").
  domain: template
  input:
    child_name:
      name: Child Name
      description: Name of the child to monitor
      selector:
        text:
    trusted_adults:
      name: Trusted Adults
      description: List of adult names (as detected by Frigate)
      default: ["Dad", "Mom"]
      selector:
        object:
    supervision_timeout:
      name: Supervision Timeout
      description: How many seconds since adult was seen to still consider supervised
      default: 60
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    manual_override_entity:
      name: Manual Override Entity (Optional)
      description: Input boolean to manually mark child as supervised
      default: ""
      selector:
        entity:
          domain: input_boolean

binary_sensor:
  - name: "{{ child_name }} Supervised"
    unique_id: "{{ child_name.lower() }}_supervised"
    state: >
      {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
      {% if not persons or child_name not in persons %}
        {{ false }}
      {% else %}
        {% set child = persons[child_name] %}
        {% set child_camera = child.camera %}
        {% set child_zones = child.frigate_zones %}
        {% set now = as_timestamp(now()) %}
        {% set adults = trusted_adults %}
        {% set supervised = namespace(value=false) %}

        {% for adult in adults %}
          {% if adult in persons %}
            {% set adult_data = persons[adult] %}
            {% set adult_time = as_timestamp(adult_data.last_seen) %}

            {% if (now - adult_time) < supervision_timeout %}
              {# Same camera is always sufficient #}
              {% if adult_data.camera == child_camera %}
                {% set supervised.value = true %}
              {# Also supervising when sharing an active zone (multi-camera yards) #}
              {% elif child_zones | length > 0 %}
                {% for zone in child_zones %}
                  {% if zone in adult_data.frigate_zones %}
                    {% set supervised.value = true %}
                  {% endif %}
                {% endfor %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}

        {# Allow manual override #}
        {% if manual_override_entity != '' %}
          {{ supervised.value or is_state(manual_override_entity, 'on') }}
        {% else %}
          {{ supervised.value }}
        {% endif %}
      {% endif %}
    device_class: presence
    attributes:
      supervising_adult: >
        {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
        {% if not persons or child_name not in persons %}
          null
        {% else %}
          {% set child = persons[child_name] %}
          {% set child_camera = child.camera %}
          {% set child_zones = child.frigate_zones %}
          {% set now = as_timestamp(now()) %}
          {% set adults = trusted_adults %}

          {% for adult in adults %}
            {% if adult in persons %}
              {% set adult_data = persons[adult] %}
              {% set adult_time = as_timestamp(adult_data.last_seen) %}

              {% if (now - adult_time) < supervision_timeout %}
                {% if adult_data.camera == child_camera %}
                  {{ adult }}
                {% elif child_zones | length > 0 %}
                  {% for zone in child_zones %}
                    {% if zone in adult_data.frigate_zones %}
                      {{ adult }}
                    {% endif %}
                  {% endfor %}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
