blueprint:
  name: Frigate Identity - Supervision Detection
  description: >
    Create a binary sensor that detects if a child is supervised.

    Each Frigate camera is mapped to a logical supervision zone via the
    camera_zones input.  An adult and child are considered co-located — and
    therefore supervised — when both were seen within the timeout window AND
    their cameras resolve to the same zone name.

    Example: cameras "backyard" and "patio" both map to zone "back_yard".
    Dad on the patio is supervising Alice in the backyard because they share
    the same logical zone.

    When camera_zones is empty ({}) supervision requires the same camera,
    which is the safe default for single-camera setups.

    Note: Frigate zones are pixel-regions scoped to one camera and cannot be
    used for cross-camera supervision checks — use camera_zones instead.
  domain: template
  input:
    child_name:
      name: Child Name
      description: Name of the child to monitor
      selector:
        text:
    trusted_adults:
      name: Trusted Adults
      description: List of adult names (as detected by Frigate)
      default: ["Dad", "Mom"]
      selector:
        object:
    camera_zones:
      name: Camera Zone Mapping
      description: >
        Map each Frigate camera name to a logical supervision zone.
        Cameras with the same zone name are treated as covering the same
        physical area.  Leave empty ({}) to require the same camera.
        Example: {backyard: back_yard, patio: back_yard, front_door: front_entry}
      default: {}
      selector:
        object:
    supervision_timeout:
      name: Supervision Timeout
      description: How many seconds since adult was seen to still consider supervised
      default: 60
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    manual_override_entity:
      name: Manual Override Entity (Optional)
      description: Input boolean to manually mark child as supervised
      default: ""
      selector:
        entity:
          domain: input_boolean

binary_sensor:
  - name: "{{ child_name }} Supervised"
    unique_id: "{{ child_name.lower() }}_supervised"
    state: >
      {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
      {% if not persons or child_name not in persons %}
        {{ false }}
      {% else %}
        {% set child_camera = persons[child_name].camera %}
        {% set cz = camera_zones %}
        {% set child_zone = cz.get(child_camera, child_camera) %}
        {% set now = as_timestamp(now()) %}
        {% set adults = trusted_adults %}
        {% set supervised = namespace(value=false) %}

        {% for adult in adults %}
          {% if adult in persons %}
            {% set adult_time = as_timestamp(persons[adult].last_seen) %}
            {% if (now - adult_time) < supervision_timeout %}
              {% set adult_zone = cz.get(persons[adult].camera, persons[adult].camera) %}
              {% if adult_zone == child_zone %}
                {% set supervised.value = true %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}

        {% if manual_override_entity != '' %}
          {{ supervised.value or is_state(manual_override_entity, 'on') }}
        {% else %}
          {{ supervised.value }}
        {% endif %}
      {% endif %}
    device_class: presence
    attributes:
      supervising_adult: >
        {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
        {% if not persons or child_name not in persons %}
          null
        {% else %}
          {% set child_camera = persons[child_name].camera %}
          {% set cz = camera_zones %}
          {% set child_zone = cz.get(child_camera, child_camera) %}
          {% set now = as_timestamp(now()) %}
          {% set adults = trusted_adults %}

          {% for adult in adults %}
            {% if adult in persons %}
              {% set adult_time = as_timestamp(persons[adult].last_seen) %}
              {% if (now - adult_time) < supervision_timeout %}
                {% set adult_zone = cz.get(persons[adult].camera, persons[adult].camera) %}
                {% if adult_zone == child_zone %}
                  {{ adult }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
