blueprint:
  name: Frigate Identity - Supervision Detection
  description: >
    Create a binary sensor that detects if a child is supervised.

    Zone resolution uses a three-level priority:

    1. Explicit override from camera_zones_override (for cameras not in an HA Area)
    2. HA Area assignment — area_name('camera.<name>') resolved automatically
    3. Camera name fallback (same-camera only)

    If your Frigate cameras are already assigned to Areas in Home Assistant
    (Settings → Areas & Zones), no extra configuration is needed — the sensor
    resolves supervision zones from HA automatically.

    camera_zones_override is only needed for cameras that are NOT assigned to
    an HA Area, or when a different grouping than the HA Area is desired.

    Note: Frigate zones are pixel-regions scoped to one camera and cannot be
    used for cross-camera supervision checks.
  domain: template
  input:
    child_name:
      name: Child Name
      description: Name of the child to monitor
      selector:
        text:
    trusted_adults:
      name: Trusted Adults
      description: List of adult names (as detected by Frigate)
      default: ["Dad", "Mom"]
      selector:
        object:
    camera_zones_override:
      name: Camera Zone Overrides (Optional)
      description: >
        Only needed if your Frigate cameras are NOT assigned to HA Areas, or
        you want a different grouping than the HA Area provides.
        Map camera names to supervision zones.
        Example: {backyard: back_yard, patio: back_yard}
        Leave as {} if cameras are already assigned to HA Areas.
      default: {}
      selector:
        object:
    supervision_timeout:
      name: Supervision Timeout
      description: How many seconds since adult was seen to still consider supervised
      default: 60
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    manual_override_entity:
      name: Manual Override Entity (Optional)
      description: Input boolean to manually mark child as supervised
      default: ""
      selector:
        entity:
          domain: input_boolean

binary_sensor:
  - name: "{{ child_name }} Supervised"
    unique_id: "{{ child_name.lower() }}_supervised"
    state: >
      {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
      {% if not persons or child_name not in persons %}
        {{ false }}
      {% else %}
        {% set child_camera = persons[child_name].camera %}
        {% set overrides = camera_zones_override %}
        {% set child_zone = overrides.get(child_camera)
                            or area_name('camera.' ~ child_camera)
                            or child_camera %}
        {% set now = as_timestamp(now()) %}
        {% set adults = trusted_adults %}
        {% set supervised = namespace(value=false) %}

        {% for adult in adults %}
          {% if adult in persons %}
            {% set adult_time = as_timestamp(persons[adult].last_seen) %}
            {% if (now - adult_time) < supervision_timeout %}
              {% set adult_cam = persons[adult].camera %}
              {% set adult_zone = overrides.get(adult_cam)
                                  or area_name('camera.' ~ adult_cam)
                                  or adult_cam %}
              {% if adult_zone == child_zone %}
                {% set supervised.value = true %}
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}

        {% if manual_override_entity != '' %}
          {{ supervised.value or is_state(manual_override_entity, 'on') }}
        {% else %}
          {{ supervised.value }}
        {% endif %}
      {% endif %}
    device_class: presence
    attributes:
      supervising_adult: >
        {% set persons = state_attr('sensor.frigate_identity_all_persons', 'persons') %}
        {% if not persons or child_name not in persons %}
          null
        {% else %}
          {% set child_camera = persons[child_name].camera %}
          {% set overrides = camera_zones_override %}
          {% set child_zone = overrides.get(child_camera)
                              or area_name('camera.' ~ child_camera)
                              or child_camera %}
          {% set now = as_timestamp(now()) %}
          {% set adults = trusted_adults %}

          {% for adult in adults %}
            {% if adult in persons %}
              {% set adult_time = as_timestamp(persons[adult].last_seen) %}
              {% if (now - adult_time) < supervision_timeout %}
                {% set adult_cam = persons[adult].camera %}
                {% set adult_zone = overrides.get(adult_cam)
                                    or area_name('camera.' ~ adult_cam)
                                    or adult_cam %}
                {% if adult_zone == child_zone %}
                  {{ adult }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
